# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-12-09 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20201209_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricepolicy',
            old_name='project_size',
            new_name='per_file_size',
        ),
    ]
