# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20201209_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='count',
            field=models.IntegerField(help_text='0表示无限期', verbose_name='数量/（年）'),
        ),
    ]
